apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  selector:
    app: orderservice  # Matches the deployment's label selector
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer  # This will expose the service externally (for Minikube)
